language: node_js

node_js:
  - 11

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - npm ci

before_script:
  - npm install -g @angular/cli

script:
  - npm install
  - npm run build --prod
deploy:
  skip_cleanup: true
  provider: firebase